name: Build and Deploy DEV

on:
  push:
    branches: ["dev"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-18.04
    environment: development

    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.3
          cache: npm

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Stop Remote Service
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script_stop: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            PATH=$PATH:/${{secrets.REMOTE_USER}}/.npm-global/bin
            pm2 delete my-stream-app || true
            rm -r ${{secrets.DEPLOY_PATH}} || true

      - name: Copy Files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          source: "./"
          target: ${{secrets.DEPLOY_PATH}}

      - name: Start Remote Service
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script_stop: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            PATH=$PATH:/${{secrets.REMOTE_USER}}/.npm-global/bin
            cd ${{secrets.DEPLOY_PATH}}
            pm2 start cross-env --name my-stream-app -- NODE_ENV=development npm run start

  health-check:
    needs: deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Ping the Server
        run: curl --connect-timeout 5 ${{secrets.REMOTE_HOST}}:${{secrets.DEPLOY_PORT}}/api/health-check
